eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/
server:
  port: 4444
spring:
  application:
    name: gateway
zuul:
  routes:
    api:
      path: /api/**
      serviceId: eurekaclient